using FluentValidation;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Moe.Application.Abstractions.Audit;
using Moe.Application.Abstractions.Messaging;
using Moe.Application.Abstractions.Modules;
using Moe.Application.Abstractions.Persistence;
using Moe.Application.Abstractions.Security;
using Moe.Modules.IdentityPlatform.Api.Admin;
using Moe.Modules.IdentityPlatform.Api.EService;
using Moe.Modules.IdentityPlatform.Application.Access.AssignAccessScope;
using Moe.Modules.IdentityPlatform.Application.Access.RevokeAccessScope;
using Moe.Modules.IdentityPlatform.Application.AdminProfile;
using Moe.Modules.IdentityPlatform.Application.AdminProfile.GetMyAdminProfile;
using Moe.Modules.IdentityPlatform.Application.AdminProfile.UpdateMyAdminContact;
using Moe.Modules.IdentityPlatform.Application.AdminAccountDetails;
using Moe.Modules.IdentityPlatform.Application.AdminStudentList;
using Moe.Modules.IdentityPlatform.Application.AdminUsers.CreateAdminUser;
using Moe.Modules.IdentityPlatform.Application.Authentication.GetAdminAuthFlow;
using Moe.Modules.IdentityPlatform.Application.Authentication.GetCurrentIdentity;
using Moe.Modules.IdentityPlatform.Application.Authentication.GetEServiceAuthFlow;
using Moe.Modules.IdentityPlatform.Application.ExternalProvisioning;
using Moe.Modules.IdentityPlatform.Application.ExternalProvisioning.DisableUserAccount;
using Moe.Modules.IdentityPlatform.Application.ExternalProvisioning.ProvisionStudentSingpassAccount;
using Moe.Modules.IdentityPlatform.Application.ExternalProvisioning.RetryIdentityProvisioning;
using Moe.Modules.IdentityPlatform.Application.ReferenceData;
using Moe.Modules.IdentityPlatform.Application.StudentProfile;
using Moe.Modules.IdentityPlatform.Application.StudentProfile.GetMyStudentProfile;
using Moe.Modules.IdentityPlatform.Application.StudentProfile.UpdateMyStudentContact;
using Moe.Modules.IdentityPlatform.Application.Students.CreateStudent;
using Moe.Modules.IdentityPlatform.IGateway.Admin;
using Moe.Modules.IdentityPlatform.IGateway.AdminDashboard;
using Moe.Modules.IdentityPlatform.IGateway.Accounts;
using Moe.Modules.IdentityPlatform.IGateway.Authentication;
using Moe.Modules.IdentityPlatform.IGateway.People;
using Moe.Modules.IdentityPlatform.IGateway.Repositories;
using Moe.Modules.IdentityPlatform.IGateway.Students;
using Moe.Modules.IdentityPlatform.Infrastructure.AdminDashboard;
using Moe.Modules.IdentityPlatform.Infrastructure.Audit;
using Moe.Modules.IdentityPlatform.Infrastructure.Authentication;
using Moe.Modules.IdentityPlatform.Infrastructure.Bootstrap;
using Moe.Modules.IdentityPlatform.Infrastructure.EntraWorkforce;
using Moe.Modules.IdentityPlatform.Infrastructure.People;
using Moe.Modules.IdentityPlatform.Infrastructure.Repositories;
using Moe.Modules.IdentityPlatform.Infrastructure.Singpass;
using Moe.Modules.IdentityPlatform.Infrastructure.Students;

namespace Moe.Modules.IdentityPlatform;

public sealed class IdentityPlatformModule : IModule
{
    public string Name => "IdentityPlatform";
    public void AddServices(IServiceCollection services, IConfiguration configuration)
    {
        services.AddSingleton<IModelConfigurationContributor, IdentityPlatformModelConfiguration>();
        services.AddOptions<AdminBootstrapOptions>().BindConfiguration(AdminBootstrapOptions.SectionName);
        services.AddOptions<EntraWorkforceDirectoryOptions>().BindConfiguration(EntraWorkforceDirectoryOptions.SectionName);
        services.AddHostedService<AdminBootstrapHostedService>();
        services.AddScoped<IClaimsTransformation, LocalClaimsTransformation>();
        services.AddScoped<IStudentAccessControl, StudentAccessControl>();
        services.AddScoped<IAuditService, AuditService>();
        services.AddScoped<IEServiceLoginResolver, EServiceLoginResolver>();
        services.AddHttpClient<IEntraWorkforceDirectoryClient, EntraWorkforceDirectoryClient>();
        services.AddHttpClient<ISingpassLoginGateway, MockPassFapiLoginGateway>();
        services.AddScoped<ILocalIdentityDirectory, LocalIdentityDirectory>();
        services.AddScoped<ILoginAccountDisplayDirectory, LoginAccountDisplayDirectory>();
        services.AddScoped<IAdminDashboardIdentityDirectory, AdminDashboardIdentityDirectory>();
        services.AddScoped<IStudentDirectory, StudentDirectory>();
        services.AddScoped<ITopUpStudentSearchDirectory, TopUpStudentSearchDirectory>();
        services.AddScoped<IAdminStudentListReader, AdminStudentListReader>();
        services.AddScoped<IPersonDirectory, PersonDirectory>();
        services.AddScoped<IPersonLifecycleGateway, PersonLifecycleGateway>();
        services.AddScoped<IUserAccountRepository, UserAccountRepository>();
        services.AddScoped<IExternalIdentityProvisioningRepository, UserAccountRepository>();
        services.AddScoped<IAdminUserRepository, AdminUserRepository>();
        services.AddScoped<IAccessScopeRepository, AccessScopeRepository>();
        services.AddScoped<IOrganizationUnitRepository, OrganizationUnitRepository>();
        services.AddScoped<IStudentOnboardingRepository, StudentOnboardingRepository>();
        services.AddScoped<IIdentityProvisioningRequestRepository, IdentityProvisioningRequestRepository>();
        services.AddScoped<IStudentSingpassProvisioningRepository, StudentSingpassProvisioningRepository>();
        services.AddScoped<IStudentProfileRepository, StudentProfileRepository>();
        services.AddScoped<IAdminAccountDetailsRepository, AdminAccountDetailsRepository>();
        services.AddScoped<ILocalIdentityRepository, LocalIdentityRepository>();
        services.AddScoped<IQueryHandler<GetAdminAuthFlowQuery, AdminAuthFlowResponse>, GetAdminAuthFlowHandler>();
        services.AddScoped<IQueryHandler<GetCurrentIdentityQuery, LocalIdentitySummary>, GetCurrentIdentityHandler>();
        services.AddScoped<IQueryHandler<GetEServiceAuthFlowQuery, EServiceAuthFlowResponse>, GetEServiceAuthFlowHandler>();
        services.AddScoped<IQueryHandler<GetMyAdminProfileQuery, AdminProfileResponse>, GetMyAdminProfileHandler>();
        services.AddScoped<IQueryHandler<GetMyStudentProfileQuery, StudentProfileResponse>, GetMyStudentProfileHandler>();
        services.AddScoped<IQueryHandler<GetAdminAccountDetailsQuery, AdminAccountDetailsResponse>, GetAdminAccountDetailsHandler>();
        services.AddScoped<IQueryHandler<ListAdminStudentsQuery, AdminStudentListPage>, ListAdminStudentsHandler>();
        services.AddScoped<IQueryHandler<ListAdminStudentClassesQuery, IReadOnlyList<string>>, ListAdminStudentClassesHandler>();
        services.AddScoped<IQueryHandler<GetStudentManagementReferenceDataQuery, StudentManagementReferenceDataResponse>, GetStudentManagementReferenceDataHandler>();
        services.AddScoped<ICommandHandler<CreateAdminUserCommand, CreateAdminUserResponse>, CreateAdminUserHandler>();
        services.AddScoped<ICommandHandler<CreateStudentCommand, CreateStudentResponse>, CreateStudentHandler>();
        services.AddScoped<ICommandHandler<UpdateMyAdminContactCommand, AdminProfileResponse>, UpdateMyAdminContactHandler>();
        services.AddScoped<ICommandHandler<UpdateMyStudentContactCommand, StudentProfileResponse>, UpdateMyStudentContactHandler>();
        services.AddScoped<ICommandHandler<UpdateAdminAccountDetailsCommand, AdminAccountDetailsResponse>, UpdateAdminAccountDetailsHandler>();
        services.AddScoped<IQueryHandler<GetIdentityProvisioningRequestQuery, IdentityProvisioningRequestResponse>, GetIdentityProvisioningRequestHandler>();
        services.AddScoped<ICommandHandler<AssignAccessScopeCommand, AssignAccessScopeResponse>, AssignAccessScopeHandler>();
        services.AddScoped<ICommandHandler<DisableUserAccountCommand, DisableUserAccountResponse>, DisableUserAccountHandler>();
        services.AddScoped<ICommandHandler<ProvisionStudentSingpassAccountCommand, ProvisionStudentSingpassAccountResponse>, ProvisionStudentSingpassAccountHandler>();
        services.AddScoped<ICommandHandler<RetryIdentityProvisioningCommand, IdentityProvisioningRequestResponse>, RetryIdentityProvisioningHandler>();
        services.AddScoped<ICommandHandler<RevokeAccessScopeCommand, RevokeAccessScopeResponse>, RevokeAccessScopeHandler>();
        services.AddScoped<IValidator<AssignAccessScopeCommand>, AssignAccessScopeValidator>();
        services.AddScoped<IValidator<CreateAdminUserCommand>, CreateAdminUserValidator>();
        services.AddScoped<IValidator<CreateStudentCommand>, CreateStudentValidator>();
        services.AddScoped<IValidator<UpdateMyAdminContactCommand>, UpdateMyAdminContactValidator>();
        services.AddScoped<IValidator<UpdateMyStudentContactCommand>, UpdateMyStudentContactValidator>();
        services.AddScoped<IValidator<UpdateAdminAccountDetailsCommand>, UpdateAdminAccountDetailsValidator>();
        services.AddScoped<IValidator<ProvisionStudentSingpassAccountCommand>, ProvisionStudentSingpassAccountValidator>();
        services.AddScoped<IValidator<AssignAccessScopeRequest>, AssignAccessScopeRequestValidator>();
        services.AddScoped<IValidator<CreateAdminUserRequest>, CreateAdminUserRequestValidator>();
        services.AddScoped<IValidator<CreateStudentRequest>, CreateStudentRequestValidator>();
        services.AddScoped<IValidator<UpdateMyAdminContactRequest>, UpdateMyAdminContactRequestValidator>();
        services.AddScoped<IValidator<UpdateMyStudentContactRequest>, UpdateMyStudentContactRequestValidator>();
        services.AddScoped<IValidator<UpdateAdminAccountDetailsRequest>, UpdateAdminAccountDetailsRequestValidator>();
        services.AddScoped<IValidator<ProvisionStudentSingpassAccountRequest>, ProvisionStudentSingpassAccountRequestValidator>();
    }
    public void MapEndpoints(IEndpointRouteBuilder endpoints) { }
}
