// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Moe.StudentFinance.Persistence;

#nullable disable

namespace Moe.StudentFinance.Migrations.Migrations
{
    [DbContext(typeof(MoeDbContext))]
    [Migration("20260624074000_AddEducationAccountLifecycleRunHistory")]
    public partial class AddEducationAccountLifecycleRunHistory
    {
    }
}
