namespace Moe.Application.Abstractions.Audit;

public static class AuditActionCodes
{
    public const string EducationAccountCreatedManually = "EDUCATION_ACCOUNT_CREATED_MANUALLY";
    public const string EducationAccountCreatedAutomatically = "EDUCATION_ACCOUNT_CREATED_AUTOMATICALLY";
    public const string EducationAccountClosedManually = "EDUCATION_ACCOUNT_CLOSED_MANUALLY";
    public const string EducationAccountClosedAutomatically = "EDUCATION_ACCOUNT_CLOSED_AUTOMATICALLY";
    public const string AccountDetailsUpdatedByAdmin = "ACCOUNT_DETAILS_UPDATED_BY_ADMIN";
    public const string AdminLogin = "ADMIN_LOGIN";
    public const string AdminLogout = "ADMIN_LOGOUT";
    public const string StudentLogin = "STUDENT_LOGIN";
    public const string StudentLogout = "STUDENT_LOGOUT";
    public const string StudentCreated = "STUDENT_CREATED";
    public const string StudentBulkImportCompleted = "STUDENT_BULK_IMPORT_COMPLETED";
    public const string StudentContactUpdated = "STUDENT_CONTACT_UPDATED";
    public const string UserAccountDisabled = "USER_ACCOUNT_DISABLED";
    public const string UserAccountEnabled = "USER_ACCOUNT_ENABLED";
    public const string CourseCreated = "COURSE_CREATED";
    public const string CourseUpdated = "COURSE_UPDATED";
    public const string CoursePublished = "COURSE_PUBLISHED";
    public const string CourseDisabled = "COURSE_DISABLED";
    public const string CourseEnabled = "COURSE_ENABLED";
    public const string CourseDeleted = "COURSE_DELETED";
    public const string CourseEnrollmentCreatedByAdmin = "COURSE_ENROLLMENT_CREATED_BY_ADMIN";
    public const string CourseEnrollmentRemovedByAdmin = "COURSE_ENROLLMENT_REMOVED_BY_ADMIN";
    public const string PaymentCompleted = "PAYMENT_COMPLETED";
    public const string PaymentFailed = "PAYMENT_FAILED";
    public const string PaymentCancelled = "PAYMENT_CANCELLED";
    public const string RefundRequestedByAdmin = "REFUND_REQUESTED_BY_ADMIN";
    public const string RefundCompleted = "REFUND_COMPLETED";
    public const string TopUpCampaignCreated = "TOPUP_CAMPAIGN_CREATED";
    public const string TopUpCampaignUpdated = "TOPUP_CAMPAIGN_UPDATED";
    public const string TopUpCampaignStatusChanged = "TOPUP_CAMPAIGN_STATUS_CHANGED";
    public const string TopUpRulesUpdated = "TOPUP_RULES_UPDATED";
    public const string TopUpFixedRecipientsUpdated = "TOPUP_FIXED_RECIPIENTS_UPDATED";
    public const string TopUpManualRunRequested = "TOPUP_MANUAL_RUN_REQUESTED";
    public const string FasSchemeCreated = "FAS_SCHEME_CREATED";
    public const string FasSchemeUpdated = "FAS_SCHEME_UPDATED";
    public const string FasSchemePublished = "FAS_SCHEME_PUBLISHED";
    public const string FasSchemeDisabled = "FAS_SCHEME_DISABLED";
    public const string FasSchemeDeleted = "FAS_SCHEME_DELETED";
    public const string FasApplicationCreated = "FAS_APPLICATION_CREATED";
    public const string FasApplicationSubmitted = "FAS_APPLICATION_SUBMITTED";
    public const string FasApplicationWithdrawn = "FAS_APPLICATION_WITHDRAWN";
    public const string FasApplicationApproved = "FAS_APPLICATION_APPROVED";
    public const string FasApplicationRejected = "FAS_APPLICATION_REJECTED";
    public const string FasSchemeSelectionWithdrawn = "FAS_SCHEME_SELECTION_WITHDRAWN";
    public const string FasSchemeSelectionCancelled = "FAS_SCHEME_SELECTION_CANCELLED";
}
